[DEBUG] 2020-11-28 06:13:10,047 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:14:10,181 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:15:10,323 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:16:10,482 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:17:10,607 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:18:10,731 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:19:10,861 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:20:11,004 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:21:11,146 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:22:11,264 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:23:11,417 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:24:11,559 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:25:11,690 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:26:11,842 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:27:11,984 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:28:12,118 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:29:12,252 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:30:12,394 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:31:12,516 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:32:12,643 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:33:12,788 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:34:12,968 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:35:13,097 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:36:13,249 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:37:13,381 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:38:13,528 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:39:13,682 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:40:13,817 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:41:13,937 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:42:14,075 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:43:14,206 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:44:14,353 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:45:14,485 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:46:14,607 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:47:14,754 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:48:14,892 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:49:15,013 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:50:15,126 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:51:15,268 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:52:15,413 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:53:15,565 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:54:15,678 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:55:15,795 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:56:15,946 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:57:16,090 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:58:16,222 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 06:59:16,381 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:00:16,529 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:01:16,655 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:02:16,777 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:03:16,927 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:04:17,072 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:05:17,191 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:06:17,345 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:07:17,477 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:08:17,622 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:09:17,752 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:10:17,877 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:11:18,013 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:12:18,159 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:13:18,303 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:14:18,438 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:15:18,555 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:16:18,682 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:17:18,807 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:18:18,932 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:19:19,081 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:20:19,215 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:21:19,370 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:22:19,555 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:23:19,677 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:24:19,859 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:25:19,989 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:26:20,110 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:27:20,237 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:28:20,374 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:29:20,493 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:30:20,623 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:31:20,747 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:32:20,896 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:33:21,044 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:34:21,167 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:35:21,348 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:36:21,495 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:37:21,635 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:38:21,785 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:39:21,923 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:40:22,066 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:41:22,189 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:42:22,299 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:43:22,453 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:44:22,596 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:45:22,737 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:46:22,877 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:47:22,995 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:48:23,143 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:49:23,282 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:50:23,400 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:51:23,528 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:52:23,665 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:53:23,793 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:54:23,924 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:55:24,031 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:56:24,186 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:57:24,350 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:58:24,486 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 07:59:24,661 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:00:24,839 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:01:25,112 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:02:25,304 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:03:25,428 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:04:25,577 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:05:25,703 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:06:25,830 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:07:25,956 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:08:26,093 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:09:26,214 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:10:26,358 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:11:26,494 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:12:26,637 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:13:26,751 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:14:26,875 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:15:27,023 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:16:27,152 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:17:27,265 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:18:27,422 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:19:27,532 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:20:27,675 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:21:27,825 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 08:23:33,255 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 08:23:33,442 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 08:23:33.255543-127.0.0.1-47e
[DEBUG] 2020-11-28 08:24:32,406 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:25:32,535 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:26:32,668 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:27:32,800 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:29:28,663 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:30:28,830 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:31:28,960 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 08:31:37,304 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 08:31:37,528 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 08:31:37.304888-127.0.0.1-585
[DEBUG] 2020-11-28 08:32:36,251 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:33:36,414 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 08:34:18,449 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 08:34:18,528 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 08:34:18.450245-127.0.0.1-b0d
[DEBUG] 2020-11-28 08:35:16,591 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:36:16,747 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:37:16,897 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:38:17,022 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:39:17,132 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 08:41:39,500 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 08:41:39,639 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 08:41:39.501045-127.0.0.1-2aa
[DEBUG] 2020-11-28 08:42:38,956 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:43:39,099 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 08:44:45,163 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 08:44:45,336 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 08:44:45.164202-127.0.0.1-f5b
[DEBUG] 2020-11-28 08:45:44,072 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:46:44,216 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:47:44,341 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:48:44,521 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:49:44,649 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:50:44,784 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 08:51:23,219 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 08:51:23,386 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 08:51:23.219951-127.0.0.1-8d0
[DEBUG] 2020-11-28 08:52:22,234 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:53:22,368 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:54:22,471 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:55:22,639 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:56:22,798 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:57:22,907 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:58:23,038 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 08:59:23,143 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:00:23,313 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:01:23,417 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:02:23,531 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:03:23,703 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:04:23,910 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:05:24,041 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:06:24,173 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:07:24,313 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:08:24,468 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:09:24,572 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:10:24,737 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:11:24,914 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:12:25,052 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:13:25,168 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:14:25,320 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:15:25,454 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:16:25,584 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:17:25,693 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:18:25,805 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:19:25,941 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:20:26,070 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:21:26,233 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:22:26,347 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 09:22:54,670 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 09:22:55,824 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 09:22:54.679881-127.0.0.1-884
[DEBUG] 2020-11-28 09:23:53,549 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:24:53,768 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:25:53,887 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:26:54,028 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:27:54,179 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:28:54,340 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:29:54,473 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:30:54,615 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:31:54,763 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:32:54,894 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 09:33:54,058 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 09:33:54,217 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 09:33:54.058699-127.0.0.1-c63
[DEBUG] 2020-11-28 09:34:53,117 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 09:36:49,102 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 09:36:49,181 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 09:36:49.103052-127.0.0.1-59f
[DEBUG] 2020-11-28 09:37:46,775 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:38:46,930 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:39:47,037 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 09:40:47,188 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 10:02:43,715 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 10:02:43,801 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 10:02:43.715571-127.0.0.1-9a7
[DEBUG] 2020-11-28 10:03:42,625 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:04:42,812 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:05:42,948 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:06:43,086 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:07:43,237 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:08:43,359 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:09:43,465 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 10:10:36,491 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 10:10:36,636 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 10:10:36.491978-127.0.0.1-fcd
[DEBUG] 2020-11-28 10:11:35,542 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 10:12:08,706 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 10:12:08,880 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 10:12:08.707509-127.0.0.1-b51
[DEBUG] 2020-11-28 10:13:08,069 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:14:08,228 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:15:08,359 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 10:16:17,167 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 10:16:17,354 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 10:16:17.167625-127.0.0.1-eb9
[DEBUG] 2020-11-28 10:17:16,158 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 10:18:12,876 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 10:18:13,025 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 10:18:12.876543-127.0.0.1-b58
[DEBUG] 2020-11-28 10:19:11,919 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:20:12,106 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:21:12,231 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 10:21:25,314 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 10:21:25,485 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 10:21:25.315227-127.0.0.1-98f
[DEBUG] 2020-11-28 10:22:24,241 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:23:24,401 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 10:24:14,623 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 10:24:14,695 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 10:24:14.623557-127.0.0.1-892
[DEBUG] 2020-11-28 10:25:12,612 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 10:25:41,680 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 10:25:41,829 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 10:25:41.681225-127.0.0.1-92a
[DEBUG] 2020-11-28 10:26:40,776 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:27:40,889 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 10:27:51,944 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 10:27:52,117 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 10:27:51.944946-127.0.0.1-b96
[DEBUG] 2020-11-28 10:28:51,103 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:29:51,258 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:30:51,424 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 10:31:15,889 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 10:31:16,093 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 10:31:15.890080-127.0.0.1-4aa
[DEBUG] 2020-11-28 10:32:14,799 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:33:14,926 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-28 10:38:57,230 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-28 10:38:57,394 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-28 10:38:57.231251-127.0.0.1-8c3
[DEBUG] 2020-11-28 10:39:56,036 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:40:56,194 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-28 10:41:56,321 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:01:56,368 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:02:56,617 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:03:56,751 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:04:56,909 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:05:57,087 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:06:57,228 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:07:57,352 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:08:57,469 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:09:57,579 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:10:57,726 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:11:57,855 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:12:57,991 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:13:58,252 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:14:58,375 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:15:58,487 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:16:58,614 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:17:58,751 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:18:58,892 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:19:59,039 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:20:59,223 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:21:59,344 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:22:59,463 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:23:59,573 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:30:01,515 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:31:01,683 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 15:32:45,769 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 15:32:45,927 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 15:32:45.769811-127.0.0.1-49f
[DEBUG] 2020-11-30 15:33:44,662 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:34:44,797 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:35:44,949 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:36:45,092 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:37:45,234 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 15:39:36,283 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 15:39:36,456 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 15:39:36.284235-127.0.0.1-b71
[DEBUG] 2020-11-30 15:40:35,124 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:41:35,281 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 15:43:09,124 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 15:43:09,201 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 15:43:09.124406-127.0.0.1-a85
[DEBUG] 2020-11-30 15:44:08,085 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:45:08,227 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:46:08,378 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:47:08,493 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 15:47:52,655 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 15:47:52,821 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 15:47:52.656234-127.0.0.1-8b8
[DEBUG] 2020-11-30 15:48:51,233 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:49:51,388 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:50:51,517 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:51:51,673 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 15:54:00,306 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 15:54:00,381 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 15:54:00.306430-127.0.0.1-ed0
[DEBUG] 2020-11-30 15:54:58,643 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:55:58,804 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 15:56:58,966 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 15:57:52,707 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 15:57:52,843 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 15:57:52.707610-127.0.0.1-3d0
[DEBUG] 2020-11-30 15:58:51,734 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 16:00:48,767 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 16:00:48,960 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 16:00:48.768160-127.0.0.1-5da
[DEBUG] 2020-11-30 16:01:47,669 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:02:47,831 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:03:47,986 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:04:48,109 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 16:05:18,325 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 16:05:18,399 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 16:05:18.325764-127.0.0.1-00e
[DEBUG] 2020-11-30 16:06:17,271 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:07:17,423 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:08:17,556 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:09:17,687 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:10:17,837 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:11:18,000 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:12:18,164 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:13:18,323 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:14:18,453 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:15:18,575 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:16:18,760 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:17:18,894 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:18:19,041 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 16:18:46,219 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 16:18:46,421 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 16:18:46.219993-127.0.0.1-53b
[DEBUG] 2020-11-30 16:19:45,055 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:20:45,219 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:21:45,382 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:22:45,517 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:23:45,686 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:24:45,851 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:29:11,806 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:33:08,464 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:34:08,619 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:35:08,878 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:36:09,024 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 16:37:13,502 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 16:37:13,571 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 16:37:13.503039-127.0.0.1-8e5
[DEBUG] 2020-11-30 16:38:09,663 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:39:09,780 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 16:40:06,058 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 16:40:06,212 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 16:40:06.058921-127.0.0.1-b77
[DEBUG] 2020-11-30 16:41:05,105 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 16:41:52,458 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 16:41:52,625 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 16:41:52.458627-127.0.0.1-560
[DEBUG] 2020-11-30 16:42:51,498 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:43:51,608 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:44:51,746 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:45:51,863 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:46:51,967 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:47:52,106 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:48:52,249 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:49:52,372 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:50:52,524 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:51:52,648 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:52:52,802 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:53:52,944 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:54:53,066 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:55:53,193 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:56:53,343 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:57:53,481 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:58:53,625 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 16:59:53,747 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:00:53,908 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:01:54,050 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:02:54,203 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:03:54,309 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:04:54,446 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:05:54,579 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:06:54,702 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:07:54,820 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:08:54,953 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 17:09:24,984 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 17:09:25,054 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 17:09:24.984987-127.0.0.1-085
[DEBUG] 2020-11-30 17:10:22,411 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:11:22,536 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 17:11:55,834 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 17:11:55,904 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 17:11:55.835008-127.0.0.1-c37
[DEBUG] 2020-11-30 17:12:53,248 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:13:53,365 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 17:14:47,462 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 17:14:47,542 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 17:14:47.463343-127.0.0.1-c80
[DEBUG] 2020-11-30 17:15:45,305 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:16:45,448 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 17:17:23,444 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 17:17:23,517 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 17:17:23.444474-127.0.0.1-521
[DEBUG] 2020-11-30 17:18:22,348 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:19:22,493 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:20:22,630 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:21:22,758 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:23:40,548 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:26:23,470 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:27:23,582 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:28:23,764 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:29:23,875 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:30:24,017 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:31:24,130 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:32:24,313 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
